version: "3"

services:
  sonarqube:
    image: sonarqube:10.3-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_JAVAADDITIONALOPTS: "-javaagent:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.18.0.jar=web"
      SONAR_CE_JAVAADDITIONALOPTS: "-javaagent:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.18.0.jar=ce"
    volumes:
      - sonarqube1_data:/opt/sonarqube/data
      - sonarqube1_extensions:/opt/sonarqube/extensions
      - sonarqube1_logs:/opt/sonarqube/logs
      - /root/sonarqube/plugins/sonarqube-community-branch-plugin-1.18.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.18.0.jar
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql1:/var/lib/postgresql
      - postgresql1_data:/var/lib/postgresql/data

volumes:
  sonarqube1_data:
  sonarqube1_extensions:
  sonarqube1_logs:
  postgresql1:
  postgresql1_data:
